# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: PayMaster.SecretKeeper
PackageVersion: 1.1.5.75
InstallerType: msix
PackageFamilyName: SecretKeeper.App_ext3tx3jt8vvj
MinimumOSVersion: 10.0.17763.0
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://wm.mycdn.ink/secretkeeper/winget/SecretKeeper-1.1.5-75.msix
  InstallerSha256: 8749E264223111AC16F1B6A23A5C5F1F94E415D151AA22192724C2AE827FD83B
  SignatureSha256: 5BF3762C4069A0F38874F941DF34FD66E5B2590EEFAB4ED06E3FF82FC95F0C2E
ManifestType: installer
ManifestVersion: 1.12.0
