# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: PayMaster.SecretKeeper
PackageVersion: 1.1.6.76
InstallerType: msix
PackageFamilyName: SecretKeeper.App_ext3tx3jt8vvj
MinimumOSVersion: 10.0.17763.0
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://wm.mycdn.ink/secretkeeper/winget/SecretKeeper-1.1.6-76.msix
  InstallerSha256: 5E8E75AE5B4372F7EF10F900E427692154B63FFF6DC37FA96D912D5619ED2FCE
  SignatureSha256: 5AC72D706CE9659A49D8B502A82DAD1403133977ADB3E45D89BBF46B301901A3
ManifestType: installer
ManifestVersion: 1.12.0
