# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.12.0.schema.json
PackageIdentifier: PayMaster.InputFixer
PackageVersion: 1.1.6.42
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.12.0
