# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: PayMaster.SecretKeeper
PackageVersion: 1.1.4.74
InstallerType: msix
PackageFamilyName: SecretKeeper.App_ext3tx3jt8vvj
MinimumOSVersion: 10.0.17763.0
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://wm.mycdn.ink/secretkeeper/winget/SecretKeeper-1.1.4-74.msix
  InstallerSha256: C37134DDFFFC6B9A436898D746AEB47DF0E23D19DBEA8B1D2C939860595AD284
  SignatureSha256: 3F2E3E1977035431ADDE7D39AF9800FE477A11EE17863143A7DE874236D22724
ManifestType: installer
ManifestVersion: 1.12.0
