# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: PayMaster.SecretKeeper
PackageVersion: 1.1.2.69
InstallerType: msix
PackageFamilyName: SecretKeeper.App_ext3tx3jt8vvj
MinimumOSVersion: 10.0.17763.0
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerUrl: https://wm.mycdn.ink/secretkeeper/winget/SecretKeeper-1.1.2-69.msix
  InstallerSha256: 07EA0776E3DF54B2F139E812BC91C5E6A6A15B5D12900509BF213D45CBCFA326
  SignatureSha256: 5A95FDC5A3E61B08D36D3A12AAAD33DD4DFC159740210A0EAEECBD2CD174A143
ManifestType: installer
ManifestVersion: 1.12.0
