# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: Tetatet.TetatetChat
PackageVersion: 1.2.47.562
InstallerType: msix
PackageFamilyName: Tetatet.Chat_ext3tx3jt8vvj
MinimumOSVersion: 10.0.17763.0
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerUrl: https://wm.mycdn.ink/secretkeeper/winget/TetatetChat-1.2.47-562.msix
  InstallerSha256: 394CD96990A25175288B320BFF724EEDE0E383FA8D80056574B249C272CB230C
  SignatureSha256: 91DDD423A9DB874C4E7DDAEC039414C8A43C7FF5CF4856A334BC2D3F8A218EDA
ManifestType: installer
ManifestVersion: 1.12.0
